package me.juhezi.eternal.repository.local

import me.juhezi.eternal.global.Fail
import me.juhezi.eternal.global.Success
import me.juhezi.eternal.global.globalRealm
import me.juhezi.eternal.model.Record
import me.juhezi.eternal.repository.interfaces.IRecordRepo

/**
 * Auto generated by repo_generator.py
 */
class LocalRecordRepo : IRecordRepo {
    override fun add(t: Record, success: Success<Record>?, fail: Fail?) {
        globalRealm.executeTransactionAsync({
            it.copyToRealm(t)
        }, {
            success?.invoke(t)
        }, {
            fail?.invoke("Add error", it)
        })
    }

    override fun update(t: Record, success: Success<Record>?, fail: Fail?) {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun remove(id: String, success: Success<Record>?, fail: Fail?) {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun query(id: String, success: Success<Record>?, fail: Fail?) {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun queryAll(success: Success<List<Record>>?, fail: Fail?) {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

}
