package me.juhezi.eternal.repository.impl

import me.juhezi.eternal.global.Fail
import me.juhezi.eternal.global.Success
import me.juhezi.eternal.global.globalGson
import me.juhezi.eternal.model.bean.ArticleListWrapper
import me.juhezi.eternal.repository.interfaces.IArticleRepo
import me.juhezi.eternal.repository.local.LocalArticleRepo
import me.juhezi.eternal.repository.remote.RemoteArticleRepo

/**
 * Auto generated by repo_generator.py
 */
class ArticleRepo(var localRepo: IArticleRepo = LocalArticleRepo(),
                  var remoteRepo: IArticleRepo = RemoteArticleRepo()) : IArticleRepo by localRepo {

    /**
     * 导出所有的 Article
     */
    fun export(success: Success<String>?, fail: Fail?) {
        queryAll({
            success?.invoke(
                    globalGson
                            .toJson(ArticleListWrapper()
                                    .setArticles(it)))
        }, fail)
    }

}
