package me.juhezi.eternal.repository.impl

import me.juhezi.eternal.repository.interfaces.IRecordRepo
import me.juhezi.eternal.repository.local.LocalRecordRepo
import me.juhezi.eternal.repository.remote.RemoteRecordRepo

/**
 * Auto generated by repo_generator.py
 */
class RecordRepo(var localRepo: IRecordRepo = LocalRecordRepo(),
                 var remoteRepo: IRecordRepo = RemoteRecordRepo()) : IRecordRepo by localRepo {
    /*override fun add(t: Record, success: Success<Record>?, fail: Fail?) {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun update(t: Record, success: Success<Record>?, fail: Fail?) {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun remove(id: String, success: Success<Record>?, fail: Fail?) {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun query(id: String, success: Success<Record>?, fail: Fail?) {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun queryAll(success: Success<List<Record>>?, fail: Fail?) {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }*/
}
