package me.juhezi.eternal.repository.impl

import me.juhezi.eternal.repository.interfaces.IRecordRepo
import me.juhezi.eternal.repository.local.LocalRecordRepo
import me.juhezi.eternal.repository.remote.RemoteRecordRepo

/**
 * Auto generated by repo_generator.py
 */
class RecordRepo(var localRepo: IRecordRepo = LocalRecordRepo(),
                 var remoteRepo: IRecordRepo = RemoteRecordRepo()) : IRecordRepo by localRepo