
package me.juhezi.eternal.repository.interfaces

import me.juhezi.eternal.model.Article
import me.juhezi.eternal.repository.IRepo

/**
 * Auto generated by repo_generator.py
 */
interface IArticleRepo : IRepo<Article>
