
package me.juhezi.eternal.repository.interfaces

import me.juhezi.eternal.model.Record
import me.juhezi.eternal.repository.IRepo

/**
 * Auto generated by repo_generator.py
 */
interface IRecordRepo : IRepo<Record>
